# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python\Lib\TP323\Gui\ACCEUIL.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QWidget,QFileDialog,QMainWindow
from TP323.Python  import RecupFich,AnalFich,GestPreuve,ReingProcess
import sys,subprocess

class Ui_Form(QWidget):
    def __init__(self):
        super().__init__()
    def Shut_Down(self):
        exit()
    def RecupeFich(self):
        subprocess.Popen("python ./RecupFich.py",shell=True, stdout=sys.stdout)
        #p.communicate()
        exit()
        
    def Analyse_De_Fichier(self):
        subprocess.Popen("python ./AnalFich.py",shell=True, stdout=sys.stdout)
        exit()
    def Gestion_Preuve(self):
        subprocess.Popen("python ./GestPreuve.py",shell=True, stdout=sys.stdout)
        exit()
    def Reingenierie_Processus(self):
        subprocess.Popen("python ./ReingProcess.py",shell=True, stdout=sys.stdout)
        exit()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1366, 768)
        Form.setMinimumSize(QtCore.QSize(1366, 768))
        Form.setMaximumSize(QtCore.QSize(1366, 768))
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 1371, 741))
        self.label_2.setStyleSheet("background-color: rgb(69, 103, 24);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../image/ImgFond.png"))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 151, 31))
        self.label.setStyleSheet("font: 22pt \"Algerian\";\n"
"background-color: rgb(54, 52, 53);\n"
"color: rgb(192, 94, 70);\n"
"border-radius:10px")
        self.label.setObjectName("label")
        self.RecupFichier = QtWidgets.QPushButton(Form)
        self.RecupFichier.setGeometry(QtCore.QRect(454, 312, 411, 51))
        self.RecupFichier.setStyleSheet("background-color: rgb(60, 81, 34);\n"
"font: 18pt \"Algerian\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"border:2px solid black;\n"
"")
        self.RecupFichier.setObjectName("RecupFichier")
        self.RecupFichier.clicked.connect(self.RecupeFich)
        #
        #
        #
        self.AnalFich = QtWidgets.QPushButton(Form)
        self.AnalFich.setGeometry(QtCore.QRect(830, 480, 411, 51))
        self.AnalFich.setStyleSheet("background-color: rgb(60, 81, 34);\n"
"font: 18pt \"Algerian\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"border:2px solid black;\n"
"")
        self.AnalFich.setObjectName("AnalFich")
        self.AnalFich.clicked.connect(self.Analyse_De_Fichier)
        #
        #
        #
        self.GestPreuve = QtWidgets.QPushButton(Form)
        self.GestPreuve.setGeometry(QtCore.QRect(780, 650, 411, 51))
        self.GestPreuve.setStyleSheet("background-color: rgb(60, 81, 34);\n"
"font: 18pt \"Algerian\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"border:2px solid black;\n"
"")
        self.GestPreuve.setObjectName("GestPreuve")
        self.GestPreuve.clicked.connect(self.Gestion_Preuve)
        #
        #
        #
        self.ReingProcess = QtWidgets.QPushButton(Form)
        self.ReingProcess.setGeometry(QtCore.QRect(120, 650, 411, 51))
        self.ReingProcess.setStyleSheet("background-color: rgb(60, 81, 34);\n"
"font: 18pt \"Algerian\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"border:2px solid black;\n"
"")
        self.ReingProcess.setObjectName("ReingProcess")
        self.ReingProcess.clicked.connect(self.Reingenierie_Processus)
        self.QuiSommeNous = QtWidgets.QPushButton(Form)
        self.QuiSommeNous.setGeometry(QtCore.QRect(70, 480, 411, 51))
        self.QuiSommeNous.setStyleSheet("background-color: rgb(60, 81, 34);\n"
"font: 18pt \"Algerian\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"border:2px solid black;\n"
"")
        self.QuiSommeNous.setObjectName("QuiSommeNous")
        self.Arreter = QtWidgets.QPushButton(Form)
        self.Arreter.setGeometry(QtCore.QRect(155, 0, 151, 31))
        self.Arreter.setStyleSheet("background-color: rgb(104, 0, 0);\n"
"font: 12pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.Arreter.setObjectName("Arreter")
        self.Arreter.setText("STOP")
        self.Arreter.clicked.connect(self.Shut_Down)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Digital Forensic"))
        self.label.setText(_translate("Form", "ACCEUIL"))
        self.RecupFichier.setText(_translate("Form", "RECUPERATION DES FICHIERS"))
        self.AnalFich.setText(_translate("Form", "ANALYSE DES FICHIERS"))
        self.GestPreuve.setText(_translate("Form", "GESTION DES PREUVES"))
        self.ReingProcess.setText(_translate("Form", "REINGENIERIE DES PROCESSUS"))
        self.QuiSommeNous.setText(_translate("Form", "QUI SOMMES-NOUS ??"))

def main():
    app = QApplication(sys.argv)
    fen = QWidget()
    elt =Ui_Form()
    elt.setupUi(fen)
    fen.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()

