# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python\Lib\TP323\Gui\AnalyseFichier.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys,os
from os.path import basename,getatime,getmtime
from PyQt5.QtWidgets import QApplication,QWidget,QFileDialog,QMessageBox
import time
from time import gmtime,strftime,localtime
import subprocess,Acceuil,pyautogui
from TP323.Python import RecupFich, Acceuil
import os


class Ui_Form(QWidget):
    def AnalyseF(self):
         QMessageBox.information(self,"INFORMATION","Cette Fonctionnalité n'est pas encore Opérationnelle!")
    def TakeFile(self):
        fname = QFileDialog.getOpenFileName(self, 'Open file', 'c:\\')
        #print(fname)
        liste = []
        liste.append(fname)
        elt=liste
        elt2 = elt[0]
        elt3 =elt2[0]
        stat_info = os.stat(elt3)
        uid = stat_info.st_uid
        gid = stat_info.st_gid
        print (uid, gid)
        print (oct(stat_info.st_mode))
        if os.path.exists(elt3):
            self.cheminFich.clear()
            self.DateAcces.clear()
            self.DateCreat.clear()
            self.DateModif.clear()
            self.Taille.clear()
            self.TypeFich.clear()
            self.NomFich.clear()
            self.cheminFich.addItem(elt3)
            self.DroitAcces.clear()
            nom = basename(elt3).split(".")
        #date derniere acces
            DernierAcces = time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(os.path.getatime(elt3)))
            self.DateAcces.addItem(DernierAcces)
        #date de creation
            DateCreat = time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(os.path.getctime(elt3)))
            self.DateCreat.addItem(DateCreat)
        #date derniere Modif
            DernierModif = time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(os.path.getmtime(elt3)))
            self.DateModif.addItem(DernierModif)
        #la taille du fichier
            self.DroitAcces.addItem(oct(stat_info.st_mode))
            taille = os.path.getsize(elt3)
            tail = str(taille)+" 0ctects"
            self.Taille.addItem(tail)
        #Nom Du fichier
            self.NomFich.addItem(str(nom[0]))
            self.TypeFich.addItem(str(nom[1]))
            return liste
    def Go_Acceuil(self):
        subprocess.Popen("python ./Acceuil.py",shell=True, stdout=sys.stdout)
        exit()
    def Shut_Down(self):
        QApplication.exit()
    def Take_ScrenShot(self):
        myScreenshot = pyautogui.screenshot()
        #patch = str(QFileDialog.getExistingDirectory(self,"Select Directory"))
        #Chemin = patch+"\\Capture.png"
        import  random
        var =random.randint(1,100)
        QMessageBox.information(self, "INFORMATION", "Votre Capture D'ecran à été Enregistré!!\n \n Veuillez la consultée ici : C:\Python\Lib\TP323\Capture ")
        name="..\\Capture\\"+"capt"+str(var)+".png"
        myScreenshot.save(name)
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1366, 768)
        Form.setMinimumSize(QtCore.QSize(1366, 768))
        Form.setMaximumSize(QtCore.QSize(1366, 768))
        Form.setStyleSheet("background-color: rgb(70, 70, 70);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1161, 211))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../image/abstract-arrows_direction_process_magnifying-glass_search_investigate-100777420-large.jpg"))
        self.label.setObjectName("label")
        self.selectDossier = QtWidgets.QPushButton(Form)
        self.selectDossier.setGeometry(QtCore.QRect(0, 160, 281, 51))
        self.selectDossier.setStyleSheet("background-color: rgb(60, 81, 34);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black")
        self.selectDossier.setObjectName("selectDossier")
        self.selectDossier.clicked.connect(self.TakeFile)
        #
        #
        #
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(1160, 150, 201, 51))
        self.pushButton_3.setStyleSheet("background-color: rgb(60, 81, 34);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.Take_ScrenShot)
        #
        #
        #
        self.pushButton_ = QtWidgets.QPushButton(Form)
        self.pushButton_.setGeometry(QtCore.QRect(1160, 350, 201, 51))
        self.pushButton_.setStyleSheet("background-color: rgb(60, 81, 34);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black")
        self.pushButton_.setObjectName("pushButton_")
        self.pushButton_.setText("Analysé")
        self.pushButton_.clicked.connect(self.AnalyseF)
        #
        #
        #
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 40, 951, 61))
        self.label_2.setStyleSheet("background-color: rgb(157, 255, 180);\n"
"font: 60pt \"Algerian\";")
        self.label_2.setObjectName("label_2")
        self.Arreter = QtWidgets.QPushButton(Form)
        self.Arreter.setGeometry(QtCore.QRect(1160, 650, 201, 51))
        self.Arreter.setStyleSheet("background-color: rgb(104, 0, 0);\n"
"font: 12pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black")
        self.Arreter.setObjectName("Arreter")
        self.Arreter.clicked.connect(self.Shut_Down)
        #
        #
        #
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEdit.setGeometry(QtCore.QRect(1160, 0, 211, 41))
        self.dateTimeEdit.setStyleSheet("font: 16pt \"Algerian\";\n"
"background-color: rgb(255, 255, 255);")
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.Acceuil = QtWidgets.QPushButton(Form)
        self.Acceuil.setGeometry(QtCore.QRect(1160, 60, 201, 51))
        self.Acceuil.setStyleSheet("background-color: rgb(149, 67, 56);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black")
        self.Acceuil.setObjectName("Acceuil")
        self.Acceuil.clicked.connect(self.Go_Acceuil)
        #
        #
        #
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 250, 521, 21))
        self.label_3.setStyleSheet("color: rgb(9, 9, 9);\n"
"font: 26pt \"Algerian\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 300, 521, 21))
        self.label_4.setStyleSheet("color: rgb(9, 9, 9);\n"
"font: 26pt \"Algerian\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 350, 521, 21))
        self.label_5.setStyleSheet("color: rgb(9, 9, 9);\n"
"font: 26pt \"Algerian\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 400, 521, 21))
        self.label_6.setStyleSheet("color: rgb(9, 9, 9);\n"
"font: 26pt \"Algerian\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 450, 521, 21))
        self.label_7.setStyleSheet("color: rgb(9, 9, 9);\n"
"font: 26pt \"Algerian\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(10, 500, 521, 21))
        self.label_8.setStyleSheet("color: rgb(9, 9, 9);\n"
"font: 26pt \"Algerian\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(10, 550, 521, 21))
        self.label_9.setStyleSheet("color: rgb(9, 9, 9);\n"
"font: 26pt \"Algerian\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(10, 600, 521, 21))
        self.label_10.setStyleSheet("color: rgb(9, 9, 9);\n"
"font: 26pt \"Algerian\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(550, 240, 16, 31))
        self.label_11.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(550, 290, 16, 31))
        self.label_12.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(550, 340, 16, 31))
        self.label_13.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(550, 390, 16, 31))
        self.label_14.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(550, 440, 16, 31))
        self.label_15.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(550, 490, 16, 31))
        self.label_16.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(550, 540, 16, 31))
        self.label_17.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(550, 590, 16, 31))
        self.label_18.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.cheminFich = QtWidgets.QListWidget(Form)
        self.cheminFich.setGeometry(QtCore.QRect(570, 240, 591, 40))
        self.cheminFich.setStyleSheet("background-color: rgb(226, 222, 217);\n"
"font: 16pt \"Algerian\";")
        self.cheminFich.setObjectName("cheminFich")
        self.NomFich = QtWidgets.QListWidget(Form)
        self.NomFich.setGeometry(QtCore.QRect(570, 300, 591, 31))
        self.NomFich.setStyleSheet("background-color: rgb(226, 222, 217);\n"
"font: 16pt \"Algerian\";")
        self.NomFich.setObjectName("NomFich")
        self.TypeFich = QtWidgets.QListWidget(Form)
        self.TypeFich.setGeometry(QtCore.QRect(570, 350, 591, 31))
        self.TypeFich.setStyleSheet("background-color: rgb(226, 222, 217);\n"
"font: 16pt \"Algerian\";")
        self.TypeFich.setObjectName("TypeFich")
        self.DateCreat = QtWidgets.QListWidget(Form)
        self.DateCreat.setGeometry(QtCore.QRect(570, 400, 591, 31))
        self.DateCreat.setStyleSheet("background-color: rgb(226, 222, 217);\n"
"font: 16pt \"Algerian\";")
        self.DateCreat.setObjectName("DateCreat")
        self.DroitAcces = QtWidgets.QListWidget(Form)
        self.DroitAcces.setGeometry(QtCore.QRect(570, 450, 591, 31))
        self.DroitAcces.setStyleSheet("background-color: rgb(226, 222, 217);\n"
"font: 16pt \"Algerian\";")
        self.DroitAcces.setObjectName("DroitAcces")
        self.DateModif = QtWidgets.QListWidget(Form)
        self.DateModif.setGeometry(QtCore.QRect(570, 500, 591, 31))
        self.DateModif.setStyleSheet("background-color: rgb(226, 222, 217);\n"
"font: 16pt \"Algerian\";")
        self.DateModif.setObjectName("DateModif")
        self.DateAcces = QtWidgets.QListWidget(Form)
        self.DateAcces.setGeometry(QtCore.QRect(570, 550, 591, 31))
        self.DateAcces.setStyleSheet("background-color: rgb(226, 222, 217);\n"
"font: 16pt \"Algerian\";")
        self.DateAcces.setObjectName("DateAcces")
        self.Taille = QtWidgets.QListWidget(Form)
        self.Taille.setGeometry(QtCore.QRect(570, 600, 591, 31))
        self.Taille.setStyleSheet("background-color: rgb(226, 222, 217);\n"
"font: 16pt \"Algerian\";")
        self.Taille.setObjectName("Taille")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.selectDossier.setText(_translate("Form", "SELECTIONNEZ UN FICHIER"))
        self.pushButton_3.setText(_translate("Form", "CAPTURE D\'ECRAN"))
        self.label_2.setText(_translate("Form", "ANALYSE  DES   FICHIERS"))
        self.Arreter.setText(_translate("Form", "ARRETER"))
        self.Acceuil.setText(_translate("Form", "ACCEUIL"))
        self.label_3.setText(_translate("Form", "CHEMIN DU FICHIER"))
        self.label_4.setText(_translate("Form", "NOM DU FICHIER"))
        self.label_5.setText(_translate("Form", "TYPE DE FICHIER"))
        self.label_6.setText(_translate("Form", "DATE DE CREATION"))
        self.label_7.setText(_translate("Form", "DROIT D\'ACCES "))
        self.label_8.setText(_translate("Form", "DATE DERNIERE MODIFICATION"))
        self.label_9.setText(_translate("Form", "DATE DERNIERE ACCES"))
        self.label_10.setText(_translate("Form", "TAILLE"))
        self.label_11.setText(_translate("Form", ":"))
        self.label_12.setText(_translate("Form", ":"))
        self.label_13.setText(_translate("Form", ":"))
        self.label_14.setText(_translate("Form", ":"))
        self.label_15.setText(_translate("Form", ":"))
        self.label_16.setText(_translate("Form", ":"))
        self.label_17.setText(_translate("Form", ":"))
        self.label_18.setText(_translate("Form", ":"))


def main():
    app = QApplication(sys.argv)
    fen = QWidget()
    elt =Ui_Form()
    elt.setupUi(fen)
    fen.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()