# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python\Lib\TP323\Gui\GestionPreuves.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QWidget,QFileDialog,QMessageBox
import sys,os
from os.path import basename,getatime,getmtime
from TP323.Python import Acceuil
import time
from time import gmtime,strftime,localtime
import subprocess,pyautogui

class Ui_Form(QWidget):
    def Go_Acceuil(self):
        subprocess.Popen("python ./Acceuil.py",shell=True, stdout=sys.stdout)
        exit()
    def Shut_Down(self):
        QApplication.exit()
    def Take_ScrenShot(self):
        myScreenshot = pyautogui.screenshot()
        #patch = str(QFileDialog.getExistingDirectory(self,"Select Directory"))
        #Chemin = patch+"\\Capture.png"
        import  random
        var =random.randint(1,100)
        QMessageBox.information(self, "INFORMATION", "Votre Capture D'ecran à été Enregistré!!\n \n Veuillez la consultée ici : C:\Python\Lib\TP323\Capture ")
        name="..\\Capture\\"+"capt"+str(var)+".png"
        myScreenshot.save(name)
     # GESTION DE PREUVES
    #
    # 
    # 
    # 
    # 
    #
    # 
    # 
    # 
    # 
    # 
    # PILOTE
    #
    # 
    # 
    # 
    # 
    def ListePilote(self):
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"\n"
"border:3px solid black")
        self.comboBox_3.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.comboBox.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.pushButton_2.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"\n"
"border:3px solid black")
        self.comboBox_2.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.pushButton.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        #
        # 
        # 
        # 
        # 
        self.listWidget.clear()
        p = subprocess.Popen(["powershell.exe", 
              "driverquery > ..\Txt\pilote.txt"], 
              stdout=sys.stdout)
        p.communicate()
        # Ouvrir le fichier en lecture seule
        file = open('../Txt/pilote.txt', "r")
        lines = file.readlines()
        # fermez le fichier après avoir lu les lignes
        file.close()
        # Itérer sur les lignes
        for line in lines:
            #print(line.strip())
            self.listWidget.addItem(line.strip())
#
#
#
#
    def Historique_Navig(self):
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"\n"
"border:3px solid black")
        self.comboBox_3.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.comboBox.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.pushButton_2.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"\n"
"border:3px solid black")
        self.comboBox_2.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.pushButton_4.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.listWidget.clear()
        p = subprocess.Popen("ipconfig/displaydns > ..\Txt\Text.txt", shell=True)
        p.communicate()
        # Ouvrir le fichier en lecture seule
        file = open('../Txt/Text.txt', "r")
        lines = file.readlines()
        # fermez le fichier après avoir lu les lignes
        file.close()
        # Itérer sur les lignes
        for line in lines:
            #print(line.strip())
            self.listWidget.addItem(line.strip())
#
# 
# 
# 
# 
# 
# 
# 
# LOGICIEL
#
# 
# 
# 
# 
    def LogicielInstalle(self) :
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"\n"
"border:3px solid black")
        self.pushButton_4.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.comboBox_3.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.comboBox.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.pushButton.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"\n"
"border:3px solid black")
        self.comboBox_2.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        #
        # 
        # 
        # r
        self.listWidget.clear()
        p = subprocess.Popen(["powershell.exe", 
              "Get-WmiObject -Class Win32_Product | Select-Object -Property Name >  ..\Txt\logiciel.txt"], 
              stdout=sys.stdout)
        p.communicate()
        # Ouvrir le fichier en lecture seule
        file = open('..\Txt\logiciel.txt', "r")
        lines = file.readlines()
        # fermez le fichier après avoir lu les lignes
        file.close()
        # Itérer sur les lignes
        for line in lines:
            #print(line.strip())
            self.listWidget.addItem(line.strip())
#
# 
# 
# 
# 
# 
# 
# 
#
# 
# 
# 
# 
# 
# 
# 
# WIFI
# 
# 
# 
# 
# 
    def ReseauWifi(self):
        self.pushButton_4.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"\n"
"border:3px solid black")
        self.comboBox_3.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.comboBox.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.pushButton_2.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"\n"
"border:3px solid black")
        self.pushButton.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.listWidget.clear()
        if self.comboBox_2.currentText()=="Informations Réseaux":
            pass
        if self.comboBox_2.currentText()=="1--° lister les cartes réseaux physiques":
            p = subprocess.Popen(["powershell.exe", 
                  "Get-NetAdapter > ..\Txt\ListeCarteRes.txt"], 
                  stdout=sys.stdout)
            p.communicate()
            # Ouvrir le fichier en lecture seule
            file = open('..\Txt\ListeCarteRes.txt', "r")
            lines = file.readlines()
            # fermez le fichier après avoir lu les lignes
            file.close()
            # Itérer sur les lignes
            for line in lines:
            #print(line.strip())
               self.listWidget.addItem(line.strip())
        if self.comboBox_2.currentText()=="2--° lister les paramètres réseaux des cartes":
            self.listWidget.clear()
            p = subprocess.Popen(["powershell.exe", 
                  "Get-NetIpaddress > ..\Txt\ListeParamRes.txt"], 
                  stdout=sys.stdout)
            p.communicate()
            # Ouvrir le fichier en lecture seule
            file = open('..\Txt\ListeParamRes.txt', "r")
            lines = file.readlines()
            # fermez le fichier après avoir lu les lignes
            file.close()
            # Itérer sur les lignes
            for line in lines:
            #print(line.strip())
               self.listWidget.addItem(line.strip())
        if self.comboBox_2.currentText()=="3--° Afficher les informations DNS du carte réseaux":
            self.listWidget.clear()
            p = subprocess.Popen(["powershell.exe", 
                  "Get-DnsClientServerAddress > ..\Txt\ListeInfoDns.txt"], 
                  stdout=sys.stdout)
            p.communicate()
            # Ouvrir le fichier en lecture seule
            file = open('..\Txt\ListeInfoDns.txt', "r")
            lines = file.readlines()
            # fermez le fichier après avoir lu les lignes
            file.close()
            # Itérer sur les lignes
            for line in lines:
            #print(line.strip())
               self.listWidget.addItem(line.strip())
        if self.comboBox_2.currentText()=="4--° Afficher la table route":
            self.listWidget.clear()
            p = subprocess.Popen(["powershell.exe", 
                  "Get-NetRoute > ..\Txt\ListeRoute.txt"], 
                  stdout=sys.stdout)
            p.communicate()
            # Ouvrir le fichier en lecture seule
            file = open('..\Txt\ListeRoute.txt', "r")
            lines = file.readlines()
            # fermez le fichier après avoir lu les lignes
            file.close()
            # Itérer sur les lignes
            for line in lines:
            #print(line.strip())
               self.listWidget.addItem(line.strip())

#
# 
# 
# 
# 
# 
# 
#
# 
# 
# 
# 
# 
# information securité
# 
    def ComboFonction1(self):
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"\n"
"border:3px solid black")
        self.comboBox_3.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.pushButton_4.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.pushButton.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.pushButton_2.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"\n"
"border:3px solid black")
        self.comboBox_2.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.listWidget.clear()
        if self.comboBox.currentText()=="Informations sur le systéme de sécurité":
            pass
        if self.comboBox.currentText()=="2---° Liste de toutes les services":
            p = subprocess.Popen(["powershell.exe", 
                  "   gsv > ..\Txt\ListeService.txt"], 
                  stdout=sys.stdout)
            p.communicate()
            # Ouvrir le fichier en lecture seule
            file = open('..\Txt\ListeService.txt', "r")
            lines = file.readlines()
            # fermez le fichier après avoir lu les lignes
            file.close()
            # Itérer sur les lignes
            for line in lines:
            #print(line.strip())
               self.listWidget.addItem(line.strip())
        if self.comboBox.currentText()=="4---° Listes Des Warning":
            self.listWidget.clear()
            p = subprocess.Popen(["powershell.exe", 
                  " Get-EventLog System | where-object {$_.entryType -Match 'Warning'} > ..\Txt\ListeWarning.txt"], 
                  stdout=sys.stdout)
            p.communicate()
            # Ouvrir le fichier en lecture seule
            file = open('..\Txt\ListeWarning.txt', "r")
            lines = file.readlines()
            # fermez le fichier après avoir lu les lignes
            file.close()
            # Itérer sur les lignes
            for line in lines:
            #print(line.strip())
               self.listWidget.addItem(line.strip())
        if self.comboBox.currentText()=="3---° Listes des erreures Systemes":
            self.listWidget.clear()
            p = subprocess.Popen(["powershell.exe", 
                  " Get-EventLog System | where-object {$_.entryType -Match 'Error'} > ..\Txt\ListeErreur.txt"], 
                  stdout=sys.stdout)
            p.communicate()
            # Ouvrir le fichier en lecture seule
            file = open('..\Txt\ListeErreur.txt', "r")
            lines = file.readlines()
            # fermez le fichier après avoir lu les lignes
            file.close()
            # Itérer sur les lignes
            for line in lines:
            #print(line.strip())
               self.listWidget.addItem(line.strip())
        if self.comboBox.currentText()=="1---° Informations sur l'etat du System":
            self.listWidget.clear()
            p = subprocess.Popen(["powershell.exe", 
                  "Get-EventLog System | where-object {$_.entryType -Match 'Information'} >..\Txt\ListeInfo.txt"], 
                  stdout=sys.stdout)
            p.communicate()
            # Ouvrir le fichier en lecture seule
            file = open('..\Txt\ListeInfo.txt', "r")
            lines = file.readlines()
            # fermez le fichier après avoir lu les lignes
            file.close()
            # Itérer sur les lignes
            for line in lines:
            #print(line.strip())
               self.listWidget.addItem(line.strip())
#
# 
# 
# 
# 
# 
# COMBO FONCTION 2: information sur les periphériques
# 
# 
# 
# 
# 
# 
    def ComboFonction2(self):
        self.pushButton_4.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.comboBox_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"\n"
"border:3px solid black")
        self.pushButton.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.comboBox.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.pushButton_2.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"\n"
"border:3px solid black")
        self.comboBox_2.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.listWidget.clear()
        if self.comboBox_3.currentText()=="Informations sur les périphériques":
            pass
        if self.comboBox_3.currentText()=="1---° Afficher tous les périphériques (même ceux qui ne sont plus connectés)":
            p = subprocess.Popen(["powershell.exe", 
                  "get-pnpdevice > ..\Txt\ListePeriph.txt"], 
                  stdout=sys.stdout)
            p.communicate()
            # Ouvrir le fichier en lecture seule
            file = open('..\Txt\ListePeriph.txt', "r")
            lines = file.readlines()
            # fermez le fichier après avoir lu les lignes
            file.close()
            # Itérer sur les lignes
            for line in lines:
            #print(line.strip())
               self.listWidget.addItem(line.strip())
        if self.comboBox_3.currentText()=="2---° Afficher uniquement les périphériques en ligne":
            self.listWidget.clear()
            p = subprocess.Popen(["powershell.exe", 
                  "get-pnpdevice -PresentOnly > ..\Txt\ListeOnline.txt"], 
                  stdout=sys.stdout)
            p.communicate()
            # Ouvrir le fichier en lecture seule
            file = open('..\Txt\ListeOnline.txt', "r")
            lines = file.readlines()
            # fermez le fichier après avoir lu les lignes
            file.close()
            # Itérer sur les lignes
            for line in lines:
            #print(line.strip())
               self.listWidget.addItem(line.strip())
        if self.comboBox_3.currentText()=="3---° Afficher uniquement les périphériques USB en ligne":
            self.listWidget.clear()
            p = subprocess.Popen(["powershell.exe", 
                  "get-PnpDevice -Class usb -PresentOnly | ft -AutoSize > ..\Txt\ListeUsb.txt"], 
                  stdout=sys.stdout)
            p.communicate()
            # Ouvrir le fichier en lecture seule
            file = open('..\Txt\ListeUsb.txt', "r")
            lines = file.readlines()
            # fermez le fichier après avoir lu les lignes
            file.close()
            # Itérer sur les lignes
            for line in lines:
            #print(line.strip())
               self.listWidget.addItem(line.strip())
        if self.comboBox_3.currentText()=="4---° Afficher les périphériques présents et en erreur":
            self.listWidget.clear()
            p = subprocess.Popen(["powershell.exe", 
                  "get-pnpdevice -Status error,degraded -PresentOnly | ft -AutoSize > ..\Txt\ListeError.txt"], 
                  stdout=sys.stdout)
            p.communicate()
            # Ouvrir le fichier en lecture seule
            file = open('..\Txt\ListeError.txt', "r")
            lines = file.readlines()
            # fermez le fichier après avoir lu les lignes
            file.close()
            # Itérer sur les lignes
            for line in lines:
            #print(line.strip())
               self.listWidget.addItem(line.strip())
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1366, 768)
        Form.setMinimumSize(QtCore.QSize(1366, 768))
        Form.setMaximumSize(QtCore.QSize(1366, 768))
        Form.setStyleSheet("background-color: rgb(70, 70, 70);")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(440, 300, 721, 391))
        self.listWidget.setMinimumSize(QtCore.QSize(500, 300))
        self.listWidget.setMaximumSize(QtCore.QSize(1366, 500))
        self.listWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(34, 34, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black \n"
"")
        self.listWidget.setObjectName("listWidget")
        self.Arreter = QtWidgets.QPushButton(Form)
        self.Arreter.setGeometry(QtCore.QRect(1160, 640, 201, 51))
        self.Arreter.setStyleSheet("background-color: rgb(104, 0, 0);\n"
"font: 12pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.Arreter.setObjectName("Arreter")
        self.Arreter.clicked.connect(self.Shut_Down)
        #
        #
        #
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEdit.setGeometry(QtCore.QRect(1160, 0, 211, 41))
        self.dateTimeEdit.setStyleSheet("font: 16pt \"Algerian\";\n"
"background-color: rgb(255, 255, 255);")
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.Acceuil = QtWidgets.QPushButton(Form)
        self.Acceuil.setGeometry(QtCore.QRect(1160, 50, 201, 61))
        self.Acceuil.setStyleSheet("background-color: rgb(149, 67, 56);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.Acceuil.setObjectName("Acceuil")
        self.Acceuil.clicked.connect(self.Go_Acceuil)
        #
        #
        #
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(480, -40, 681, 331))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../image/cyber-forensics-degree1.jpg"))
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(1160, 240, 201, 51))
        self.pushButton_3.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.Take_ScrenShot)
        #
        #
        #
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, -50, 801, 341))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../image/cyber-forensics-degree1.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 100, 851, 61))
        self.label_2.setStyleSheet("background-color: rgb(157, 255, 180);\n"
"font: 60pt \"Algerian\";")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 320, 421, 51))
        self.pushButton.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"\n"
"border:3px solid black")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.Historique_Navig)
        #
        #
        #
        #
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 390, 421, 51))
        self.pushButton_2.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"\n"
"border:3px solid black")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.LogicielInstalle)
        #
        #
        #
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 460, 421, 51))
        self.pushButton_4.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"\n"
"border:3px solid black")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.ListePilote)
        #
        #
        #
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(10, 530, 391, 41))
        self.comboBox.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.comboBox.setObjectName("comboBox")
        #
        #
        #
        gin=["Informations sur le systéme de sécurité","1---° Informations sur l'etat du System","2---° Liste de toutes les services","3---° Listes des erreures Systemes","4---° Listes Des Warning"]
        self.comboBox.addItems(gin)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(400, 530, 31, 41))
        self.pushButton_5.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.ComboFonction1)
        #
        #
        #
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(400, 590, 31, 41))
        self.pushButton_6.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.ReseauWifi)
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 590, 391, 41))
        self.comboBox_2.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        Gina = ["Informations Réseaux","1--° lister les cartes réseaux physiques","2--° lister les paramètres réseaux des cartes","3--° Afficher les informations DNS du carte réseaux","4--° Afficher la table route"]
        self.comboBox_2.addItems(Gina)
        self.comboBox_2.setMaxVisibleItems(10)
        self.comboBox_2.setObjectName("ComboBox_2")
        #
        #
        #
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(400, 650, 31, 41))
        self.pushButton_7.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.ComboFonction2)
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 650, 391, 41))
        gin=["Informations sur les périphériques","1---° Afficher tous les périphériques (même ceux qui ne sont plus connectés)","2---° Afficher uniquement les périphériques en ligne","3---° Afficher uniquement les périphériques USB en ligne","4---° Afficher les périphériques présents et en erreur"]
        self.comboBox_3.addItems(gin)
        self.comboBox_3.setStyleSheet("background-color: rgb(118, 118, 59);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Algerian\";\n"
"border-radius:10px;\n"
"border:3px solid black ")
        self.comboBox_3.setObjectName("comboBox_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Arreter.setText(_translate("Form", "ARRETER"))
        self.Acceuil.setText(_translate("Form", "ACCEUIL"))
        self.pushButton_3.setText(_translate("Form", "CAPTURE D\'ECRAN"))
        self.label_2.setText(_translate("Form", "GESTION DES PREUVES"))
        self.pushButton.setText(_translate("Form", "HISTORIQUE DE NAVIGUATION"))
        self.pushButton_2.setText(_translate("Form", "INFORMATIONS SUR LES LOGICIELS INSTALLES"))
        self.pushButton_4.setText(_translate("Form", "INFORMATION SUR LES PILOTES"))
        self.pushButton_5.setText(_translate("Form", "OK"))
        self.pushButton_6.setText(_translate("Form", "OK"))
        self.pushButton_7.setText(_translate("Form", "OK"))

def main():
    app = QApplication(sys.argv)
    fen = QWidget()
    elt =Ui_Form()
    elt.setupUi(fen)
    fen.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
